package seamcarver;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author howezhao
 */
public class SeamCarverGUI extends javax.swing.JFrame {

    /**
     * Creates new form SeamCarverGUI
     */
    public SeamCarverGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picPathTextField = new javax.swing.JTextField();
        picPathLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        resizedWidthTextField = new javax.swing.JTextField();
        resizedWidthLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SeamCaver");

        picPathTextField.setText("picture path here...");
        picPathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picPathTextFieldActionPerformed(evt);
            }
        });

        picPathLabel.setText("picture path");

        startButton.setText("start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        resultLabel.setText("click start to process");

        refreshButton.setText("refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        resizedWidthTextField.setText("enter number in [1, 99]");
        resizedWidthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizedWidthTextFieldActionPerformed(evt);
            }
        });

        resizedWidthLabel.setText("Width after processed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshButton)
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(picPathLabel)
                            .addComponent(resizedWidthLabel))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(picPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(resizedWidthTextField))))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {refreshButton, startButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {picPathTextField, resizedWidthTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picPathLabel)
                    .addComponent(picPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resizedWidthLabel)
                    .addComponent(resizedWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(refreshButton))
                .addGap(37, 37, 37))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {picPathLabel, picPathTextField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {refreshButton, startButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {resizedWidthLabel, resizedWidthTextField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        
          
        Thread processThread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    //dispatch UI event to EDT(event dispatch thread
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            startButton.setEnabled(false);
                            resultLabel.setText("");
                            resultLabel.setText("processing...");
                        }
                    });
                    //get file path as string type
                    String path = picPathTextField.getText();
                    int percent = Integer.valueOf(resizedWidthTextField.getText());
                    if (percent <1 || percent > 99) {
                        resultLabel.setText("enter width % bewteen (1, 100)");
                        throw new java.lang.IllegalArgumentException("width percent should  bewteen (1, 100)");
                    }
                    Picture picture = new Picture(path.trim());
                    // create instance
                    SeamCarver seamCarver = new SeamCarver(picture);
                        
                    Picture greyPic = seamCarver.getGreyScalePicture();
                    progressBar.setIndeterminate(false);
                    int len = seamCarver.width() - (seamCarver.width() / 100 * percent);
                    progressBar.setMaximum(len - 1);
                    
                    for (int i = 0; i < len; i++) {
                            progressBar.setValue(i);
                            seamCarver.carvingOnce();
                    }
                    
                    Picture newPic = seamCarver.getPicture();
                    Picture newGreyPic = seamCarver.getGreyScalePicture();

                    //newPic.show();

                    greyPic.save("/Users/howezhao/Pictures/OriginalEnergyGreyScale.jpg");
                    newPic.save("/Users/howezhao/Pictures/processed.jpg");
                    newGreyPic.save("/Users/howezhao/Pictures/processedEnergyGreyScale.jpg");
                    
                    //dispatch UI event to EDT(event dispatch thread
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            resultLabel.setText("Done! processed!");
                            startButton.setEnabled(true);
                        }
                    });
                    System.out.println("Done! Processed!");
                } catch (Exception e){
                    throw new java.lang.Error(e);
                }
            }
        });//wrok Thread new End
        
        processThread.start();
        
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void picPathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picPathTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_picPathTextFieldActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        
//        new Thread(() -> {
//            resultLabel.setText("click start button to procces picture");
//        }).start();
        startButton.setEnabled(true);
        progressBar.setValue(0);
        resizedWidthTextField.setText("please enter [1, 99]");
        resultLabel.setText("reseted! click start button to procces picture");
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void resizedWidthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizedWidthTextFieldActionPerformed

        
    }//GEN-LAST:event_resizedWidthTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeamCarverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeamCarverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeamCarverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeamCarverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeamCarverGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel picPathLabel;
    private javax.swing.JTextField picPathTextField;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel resizedWidthLabel;
    private javax.swing.JTextField resizedWidthTextField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
