package seamcarver;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author howezhao
 */
public class SeamCarverGUI extends javax.swing.JFrame {

    /**
     * Creates new form SeamCarverGUI
     */
    public SeamCarverGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picPathTextField = new javax.swing.JTextField();
        picPathLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        picPathTextField.setText("path...");
        picPathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picPathTextFieldActionPerformed(evt);
            }
        });

        picPathLabel.setText("picture path");

        startButton.setText("start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        resultLabel.setText("click start to process");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(picPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(picPathLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(picPathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(picPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(startButton)
                .addGap(37, 37, 37))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {picPathLabel, picPathTextField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        
          
        Thread processThread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    startButton.setEnabled(false);
                    resultLabel.setText("");
                    resultLabel.setText("processing...");
                    //get file path as string type
                    String path = picPathTextField.getText();
                    Picture picture = new Picture(path.trim());
                    // create instance
                    SeamCarver seamCarver = new SeamCarver(picture);

                    Picture greyPic = seamCarver.getGreyScalePicture();
                    for (int i = 0; i < seamCarver.width() / 4; i++) {
                            seamCarver.CarvingOnce();
                    }

                    Picture newPic = seamCarver.getPicture();
                    Picture newGreyPic = seamCarver.getGreyScalePicture();

                    //newPic.show();

                    greyPic.save("/Users/howezhao/Pictures/OriginalEnergyGreyScale.jpg");
                    newPic.save("/Users/howezhao/Pictures/processed.jpg");
                    newGreyPic.save("/Users/howezhao/Pictures/processedEnergyGreyScale.jpg");
                    
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            resultLabel.setText("Done! processed!");
                            startButton.setEnabled(true);
                        }
                    });
                    
                } catch (Exception e){
                    throw new java.lang.Error("this is very bad");
                }
            }
        });//wrok Thread new End
        
        processThread.start();
        
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void picPathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picPathTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_picPathTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeamCarverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeamCarverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeamCarverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeamCarverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeamCarverGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel picPathLabel;
    private javax.swing.JTextField picPathTextField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
